### ISSUE TITLE
Api Calls Limit?

### ISSUE THREAD

**Issue by LudovicBouvierJohnston** [floffimedia/tasksync#1]
The script is working flawlessly. Is 5 minutes too much for a free account what is the rate for the amount of API Calls? Thank you this has been a life save for my team!

**Comment by floffimedia** [comment]
Great to hear that @LudovicBouvierJohnston, thank you very much!

So far, I have never run into any rate limits even though I’ve been testing with free accounts and one minute intervals. There seems to be a total runtime limit of 90 minutes per day for free users: https://developers.google.com/apps-script/guides/services/quotas

You can see the runtimes for your script in the _Executions_ tab.
